import type { Metadata } from "next";
<<<<<<< HEAD
import { Onest } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sileo";
import { TooltipProvider } from "@/components/ui/tooltip";
import GodProvider from "@/provider/god-provider";
import { Suspense } from "react";
const inter = Onest({
  weight: ["300", "400", "700", "100", "200", "500", "600", "800", "900"],
  subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "KinteHobe",
  description: "Your all in One E commerce",
=======
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import GodProvider from "@/provider/god-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Virtual Try On",
  description: "Generated by create next app",
>>>>>>> 9c30fdb6d669207e970434959966c84fc592eb7d
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" className={cn("h-full", "antialiased", inter.className)}>
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div>loading..</div>}>
          <GodProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </GodProvider>
        </Suspense>
        <Toaster
          position="top-left"
          options={{
            fill: "#c2ff33",
          }}
        />
=======
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <GodProvider>{children}</GodProvider>
        </TooltipProvider>
        <Toaster richColors />
>>>>>>> 9c30fdb6d669207e970434959966c84fc592eb7d
      </body>
    </html>
  );
}
