// Dummy product dataset
export const products = [
  {
    id: "PRD001",
    image: `https://placehold.net/product-400x400.png`,
    title: "Wireless Headphones",
    category: "Audio",
    price: 199.99,
    stock: 45,
    status: "active",
  },
  {
    id: "PRD002",
    image: `https://placehold.net/product-400x400.png`,
    title: "USB-C Hub",
    category: "Accessories",
    price: 49.99,
    stock: 127,
    status: "active",
  },
  {
    id: "PRD003",
    image: `https://placehold.net/product-400x400.png`,
    title: "Mechanical Keyboard",
    category: "Peripherals",
    price: 129.99,
    stock: 12,
    status: "active",
  },
  {
    id: "PRD004",
    image: `https://placehold.net/product-400x400.png`,
    title: "Wireless Mouse",
    category: "Peripherals",
    price: 39.99,
    stock: 0,
    status: "inactive",
  },
  {
    id: "PRD005",
    image: `https://placehold.net/product-400x400.png`,
    title: "4K Webcam",
    category: "Video",
    price: 99.99,
    stock: 8,
    status: "active",
  },
  {
    id: "PRD006",
    image: `https://placehold.net/product-400x400.png`,
    title: "Monitor Stand",
    category: "Accessories",
    price: 29.99,
    stock: 56,
    status: "active",
  },
  {
    id: "PRD007",
    image: `https://placehold.net/product-400x400.png`,
    title: "Portable SSD 1TB",
    category: "Storage",
    price: 89.99,
    stock: 3,
    status: "active",
  },
  {
    id: "PRD008",
    image: `https://placehold.net/product-400x400.png`,
    title: "Laptop Stand",
    category: "Accessories",
    price: 59.99,
    stock: 34,
    status: "active",
  },
];
